name: Release Process
on:
  release:
    types: [ published ]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  jsdoc:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: 🔨 Install dependencies
        run: "yarn install --pure-lockfile"

      - name: 📖 Generate JSDoc
        run: "yarn gendoc"

      - name: 📋 Copy to temp
        run: |
          ls -lah
          tag="${{ github.ref_name }}"
          version="${tag#v}"
          echo "VERSION=$version" >> $GITHUB_ENV
          cp -a "./.jsdoc/matrix-js-sdk/$version" $RUNNER_TEMP

      - name: 🧮 Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: 🌐 Deploy to Github Pages
        run: |
          cp -a "$RUNNER_TEMP/$VERSION" .

          # Add the new directory to the index if it isn't there already
          if ! grep -q "Version $VERSION" index.html; then
            perl -i -pe 'BEGIN {$rel=shift} $_ =~ /^<\/ul>/ && print
              "<li><a href=\"${rel}/index.html\">Version ${rel}</a></li>\n"' "$VERSION" index.html
          fi

          git add --all .
          git commit --no-verify -am "Add jsdoc for ${{ github.ref_name }}"
          git push origin gh-pages
