# Can be workflow_call'd only from pull_request & pull_request_review
name: Pending Reviews
on:
  pull_request:
    types: [ opened, synchronize, review_requested, review_request_removed, ready_for_review ]
  pull_request_review:
    types: [ submitted, dismissed ]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  dummy:
    name: Trigger Pending Reviews workflow_run
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am a dummy"
