# Can be workflow_call'd only from pull_request & pull_request_review
name: Pending Reviews (Run)
on:
  workflow_call:
    inputs:
      owner:
        type: string
        required: false
        description: The github username of the owner of the head branch
        default: "${{ github.event.workflow_run.head_repository.owner.login }}"
      branch:
        type: string
        required: false
        description: The name of the head branch
        default: "${{ github.event.workflow_run.head_branch }}"
  workflow_run:
    workflows: [ "Pending Reviews" ]
    types:
      - completed
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  reviews:
    name: Assert no outstanding reviews
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write
    steps:
      - name: 🔍 Check reviewers
        uses: actions/github-script@v5
        with:
          # We need to find the PR number that corresponds to the branch, which we do by searching the GH API
          # The workflow_run event includes a list of pull requests, but it doesn't get populated for
          # forked PRs: https://docs.github.com/en/rest/reference/checks#create-a-check-run
          script: |
            const [owner, repo] = "${{ github.action_repository }}".split("/");
            const pulls = await github.rest.pulls.list({
              head: "${{ inputs.owner }}:${{ inputs.branch }}",
              owner,
              repo,
            });
            const pull = pulls[0];
            const pull_number = pull.number;
            const reviews = await github.rest.pulls.listReviews({
              pull_number,
              owner,
              repo,
            });

            const pending = pull.requested_reviewers.length
              || pull.requested_teams.length
              || reviews.some(r => r.state !== "APPROVED");

            await octokit.rest.checks.create({
              conclusion: pending ? "failure" : "success",
              name: "Pending reviews",
              head_sha: pull.head.sha,
              status: "completed",
              owner,
              repo,
            });
